import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';
import Handlebars from 'handlebars';
import { differenceInYears } from 'date-fns';
import fg from 'fast-glob';
import chalk from 'chalk';
import { minify as minifyHTML } from 'html-minifier-terser';
import { minify as minifyCSS } from 'csso';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const write = (p, content) => fs.outputFileSync(path.join(root, p), content);

Handlebars.registerHelper('link', (url, text) =>
  url
    ? new Handlebars.SafeString(
        `<a href="${url}" target="_blank" rel="noopener noreferrer">${text}</a>`
      )
    : text
);

Handlebars.registerHelper('eq', (a, b) => a === b);

const computeAge = (birthdate) => differenceInYears(new Date(), new Date(birthdate));

const formatAge = (age, lang, label, translations) => {
  const pr = new Intl.PluralRules(lang);
  const category = pr.select(age);
  const unit = translations?.labels?.ageUnit?.[category] ?? 
               translations?.labels?.ageUnit?.other ?? '';
  const formatted = unit ? `${age} ${unit}` : String(age);
  return label ? `${label}: ${formatted}` : formatted;
};

const mergeTranslations = (items, translations = {}, nestedKey) =>
  items.map((item) => {
    const itemTranslation = translations[item.id] ?? {};
    const merged = { ...item, ...itemTranslation };
    
    if (nestedKey) {
      merged[nestedKey] = item[nestedKey]?.map((nested) => ({
        ...nested,
        ...(itemTranslation[nestedKey]?.[nested.id] ?? {})
      }));
    }
    
    return merged;
  });

async function build() {
  const content = yaml.load(read('data/content.yaml'));
  const builtAt = new Date().toUTCString();

  const partialFiles = fg.sync('templates/partials/*.hbs', { cwd: root });
  partialFiles.forEach((file) => {
    const name = path.basename(file, '.hbs');
    Handlebars.registerPartial(name, read(file));
  });

  const layout = Handlebars.compile(read('templates/layout.hbs'));

  const langs = ['en', 'ru'];
  const views = langs.map((lang) => {
    const t = content.i18n[lang] ?? content.i18n.en;
    const age = computeAge(content.birthdate);
    const ageText = formatAge(age, lang, t.labels?.age, t);

    return {
      lang,
      name: t.name,
      titleText: t.title,
      ageText,
      headings: t.headings,
      jobs: mergeTranslations(content.jobs, t.jobs, 'projects'),
      education: mergeTranslations(content.education, t.education),
      petProjects: mergeTranslations(content['pet-projects'], t['pet-projects']),
      contacts: content.contacts,
      pageTitle: `${t.name} - ${t.title}`,
      isDefault: lang === 'en',
    };
  });

  const html = layout({ views, builtAt });
  const htmlWithComment = `<!-- Generated from templates/layout.hbs via scripts/build.js. Do not edit this file directly. -->\n${html}`;
  
  const minifiedHTML = await minifyHTML(htmlWithComment, {
    collapseWhitespace: true,
    removeComments: false,
    minifyCSS: false,
    minifyJS: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    useShortDoctype: true
  });
  
  write('docs/index.html', minifiedHTML);
  
  fs.copySync(path.join(root, 'assets'), path.join(root, 'docs'));
  
  const css = read('src/style.css');
  const minifiedCSS = minifyCSS(css).css;
  write('docs/style.css', minifiedCSS);
  
  console.log(chalk.green('✓ Generated docs/index.html and copied static assets'));
}

build();
