import { fileURLToPath } from "node:url";
import path from "path";
import chalk from "chalk";
import fg from "fast-glob";
import fs from "fs-extra";
import Handlebars from "handlebars";
import yaml from "js-yaml";
import { minify as minifyCSS } from "csso";
import { minify as minifyHTML } from "html-minifier-terser";

import { registerHelpers, computeAge, formatAge, mergeTranslations } from "./utils.js";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDir, "..");
const read = (p) => fs.readFileSync(path.join(projectRoot, p), "utf8");
const write = (p, content) => fs.outputFileSync(path.join(projectRoot, p), content);
const outputDir = path.join(projectRoot, "build");

registerHelpers();

async function build() {
  fs.emptyDirSync(outputDir);
  const content = yaml.load(read("data/content.yaml"));
  const builtAt = new Date().toUTCString();

  const partialFiles = fg.sync("templates/partials/*.hbs", { cwd: projectRoot });
  partialFiles.forEach((file) => {
    const name = path.basename(file, ".hbs");
    Handlebars.registerPartial(name, read(file));
  });

  const layout = Handlebars.compile(read("templates/layout.hbs"));

  const langs = ["ru", "en"];
  const views = langs.map((lang) => {
    const translations = content.i18n[lang] ?? content.i18n.en;
    const age = content.birthdate ? computeAge(content.birthdate) : null;
    const ageText =
      age !== null ? formatAge(age, lang, translations.labels?.age, translations) : "";

    const headingTranslations = translations.headings ?? {};
    const buttonTranslations = translations.buttons ?? {};

    return {
      lang,
      name: translations.name,
      titleText: translations.title,
      ageText,
      headings: {
        education: headingTranslations.education,
        experience: headingTranslations.experience,
        petProjects: headingTranslations["pet-projects"],
        contacts: headingTranslations.contacts,
      },
      buttons: {
        showContacts: buttonTranslations["show-contacts"],
      },
      jobs: mergeTranslations(content.jobs, translations.jobs, "projects"),
      education: mergeTranslations(content.education, translations.education),
      petProjects: mergeTranslations(
        content["pet-projects"],
        translations["pet-projects"]
      ),
      contacts: content.contacts,
      pageTitle: `${translations.name} - ${translations.title}`,
      isDefault: lang === "ru",
    };
  });

  const html = layout({ views, builtAt });
  const htmlWithComment = `<!-- Generated from templates/layout.hbs via scripts/build.js. Do not edit this file directly. -->\n${html}`;

  const minifiedHTML = await minifyHTML(htmlWithComment, {
    collapseWhitespace: true,
    removeComments: false,
    minifyCSS: false,
    minifyJS: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    useShortDoctype: true,
  });

  write("build/index.html", minifiedHTML);

  fs.copySync(path.join(projectRoot, "assets"), outputDir);

  const css = read("src/style.css");
  const minifiedCSS = minifyCSS(css).css;
  write("build/style.css", minifiedCSS);

  console.log(
    chalk.green("✓ Generated build/index.html and copied static assets")
  );
}

build().catch((error) => {
  console.error(chalk.red("Build failed:"), error.message);
  process.exit(1);
});
