import fs from "fs-extra";
import { minify as minifyHTML } from "html-minifier-terser";

import { log } from "./log.js";
import { compileStyles, copyAssets, emptyBuild, indexPath, renderSite } from "./site.js";

try {
  await emptyBuild();

  const html = await renderSite();
  const htmlWithComment = `<!-- Generated from templates/layout.hbs via scripts/build.js. Do not edit this file directly. -->\n${html}`;
  const minifiedHTML = await minifyHTML(htmlWithComment, {
    collapseWhitespace: true,
    removeComments: false,
    minifyCSS: false,
    minifyJS: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    useShortDoctype: true,
  });

  await Promise.all([
    fs.outputFile(indexPath, minifiedHTML),
    copyAssets(),
    compileStyles({ compressed: true }),
  ]);

  log.success("Static site generated: build/index.html, build/style.css, and copied assets");
} catch (error) {
  log.error("Static site build failed:", error.message);
  process.exit(1);
}
